Search.appendIndex(
    [
                {
            "fqsen": "\\Core\\Events\\BeforeRenderEvent",
            "name": "BeforeRenderEvent",
            "summary": "",
            "url": "classes/Core-Events-BeforeRenderEvent.html"
        },                {
            "fqsen": "\\Core\\Events\\BeforeRenderEvent\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Core-Events-BeforeRenderEvent.html#method___construct"
        },                {
            "fqsen": "\\Core\\Events\\BeforeRenderEvent\u003A\u003AisPropagationStopped\u0028\u0029",
            "name": "isPropagationStopped",
            "summary": "",
            "url": "classes/Core-Events-BeforeRenderEvent.html#method_isPropagationStopped"
        },                {
            "fqsen": "\\Core\\Events\\BeforeRenderEvent\u003A\u003AstopPropagation\u0028\u0029",
            "name": "stopPropagation",
            "summary": "",
            "url": "classes/Core-Events-BeforeRenderEvent.html#method_stopPropagation"
        },                {
            "fqsen": "\\Core\\Events\\BeforeRenderEvent\u003A\u003AgetLayout\u0028\u0029",
            "name": "getLayout",
            "summary": "",
            "url": "classes/Core-Events-BeforeRenderEvent.html#method_getLayout"
        },                {
            "fqsen": "\\Core\\Events\\BeforeRenderEvent\u003A\u003AgetVars\u0028\u0029",
            "name": "getVars",
            "summary": "",
            "url": "classes/Core-Events-BeforeRenderEvent.html#method_getVars"
        },                {
            "fqsen": "\\Core\\Events\\BeforeRenderEvent\u003A\u003AgetResponseCode\u0028\u0029",
            "name": "getResponseCode",
            "summary": "",
            "url": "classes/Core-Events-BeforeRenderEvent.html#method_getResponseCode"
        },                {
            "fqsen": "\\Core\\Events\\BeforeRenderEvent\u003A\u003AgetHeaders\u0028\u0029",
            "name": "getHeaders",
            "summary": "",
            "url": "classes/Core-Events-BeforeRenderEvent.html#method_getHeaders"
        },                {
            "fqsen": "\\Core\\Events\\BeforeRenderEvent\u003A\u003AsetLayout\u0028\u0029",
            "name": "setLayout",
            "summary": "",
            "url": "classes/Core-Events-BeforeRenderEvent.html#method_setLayout"
        },                {
            "fqsen": "\\Core\\Events\\BeforeRenderEvent\u003A\u003AsetVars\u0028\u0029",
            "name": "setVars",
            "summary": "",
            "url": "classes/Core-Events-BeforeRenderEvent.html#method_setVars"
        },                {
            "fqsen": "\\Core\\Events\\BeforeRenderEvent\u003A\u003AsetVar\u0028\u0029",
            "name": "setVar",
            "summary": "",
            "url": "classes/Core-Events-BeforeRenderEvent.html#method_setVar"
        },                {
            "fqsen": "\\Core\\Events\\BeforeRenderEvent\u003A\u003AsetResponse\u0028\u0029",
            "name": "setResponse",
            "summary": "",
            "url": "classes/Core-Events-BeforeRenderEvent.html#method_setResponse"
        },                {
            "fqsen": "\\Core\\Events\\BeforeRenderEvent\u003A\u003AsetHeaders\u0028\u0029",
            "name": "setHeaders",
            "summary": "",
            "url": "classes/Core-Events-BeforeRenderEvent.html#method_setHeaders"
        },                {
            "fqsen": "\\Core\\Events\\BeforeRenderEvent\u003A\u003AsetHeader\u0028\u0029",
            "name": "setHeader",
            "summary": "",
            "url": "classes/Core-Events-BeforeRenderEvent.html#method_setHeader"
        },                {
            "fqsen": "\\Core\\Events\\BeforeRenderEvent\u003A\u003A\u0024propagationStopped",
            "name": "propagationStopped",
            "summary": "",
            "url": "classes/Core-Events-BeforeRenderEvent.html#property_propagationStopped"
        },                {
            "fqsen": "\\Core\\Events\\BeforeRenderEvent\u003A\u003A\u0024layout",
            "name": "layout",
            "summary": "",
            "url": "classes/Core-Events-BeforeRenderEvent.html#property_layout"
        },                {
            "fqsen": "\\Core\\Events\\BeforeRenderEvent\u003A\u003A\u0024responseCode",
            "name": "responseCode",
            "summary": "",
            "url": "classes/Core-Events-BeforeRenderEvent.html#property_responseCode"
        },                {
            "fqsen": "\\Core\\Events\\BeforeRenderEvent\u003A\u003A\u0024vars",
            "name": "vars",
            "summary": "",
            "url": "classes/Core-Events-BeforeRenderEvent.html#property_vars"
        },                {
            "fqsen": "\\Core\\Events\\BeforeRenderEvent\u003A\u003A\u0024headers",
            "name": "headers",
            "summary": "",
            "url": "classes/Core-Events-BeforeRenderEvent.html#property_headers"
        },                {
            "fqsen": "\\Core\\Interfaces\\AssetsCollection",
            "name": "AssetsCollection",
            "summary": "Assets\u0020collection\u0020manager",
            "url": "classes/Core-Interfaces-AssetsCollection.html"
        },                {
            "fqsen": "\\Core\\Interfaces\\AssetsCollection\u003A\u003AsetScript\u0028\u0029",
            "name": "setScript",
            "summary": "Add\u0020new\u0020script\u0020to\u0020repository",
            "url": "classes/Core-Interfaces-AssetsCollection.html#method_setScript"
        },                {
            "fqsen": "\\Core\\Interfaces\\AssetsCollection\u003A\u003AsetStyle\u0028\u0029",
            "name": "setStyle",
            "summary": "Add\u0020new\u0020style\u0020to\u0020repository",
            "url": "classes/Core-Interfaces-AssetsCollection.html#method_setStyle"
        },                {
            "fqsen": "\\Core\\Interfaces\\AssetsCollection\u003A\u003AsetCollection\u0028\u0029",
            "name": "setCollection",
            "summary": "Add\u0020new\u0020Asset\u0020collection",
            "url": "classes/Core-Interfaces-AssetsCollection.html#method_setCollection"
        },                {
            "fqsen": "\\Core\\Interfaces\\AssetsCollection\u003A\u003AgetCollection\u0028\u0029",
            "name": "getCollection",
            "summary": "Get\u0020collection\u0020of\u0020assets",
            "url": "classes/Core-Interfaces-AssetsCollection.html#method_getCollection"
        },                {
            "fqsen": "\\Core\\Interfaces\\AssetsCollection\u003A\u003AgetScriptUrl\u0028\u0029",
            "name": "getScriptUrl",
            "summary": "Get\u0020scripts\u0020URl\u0020by\u0020key",
            "url": "classes/Core-Interfaces-AssetsCollection.html#method_getScriptUrl"
        },                {
            "fqsen": "\\Core\\Interfaces\\AssetsCollection\u003A\u003AgetStyleUrl\u0028\u0029",
            "name": "getStyleUrl",
            "summary": "Get\u0020style\u0020URL\u0020by\u0020key",
            "url": "classes/Core-Interfaces-AssetsCollection.html#method_getStyleUrl"
        },                {
            "fqsen": "\\Core\\Interfaces\\AssetsCollection\u003A\u003Areset\u0028\u0029",
            "name": "reset",
            "summary": "Reset\u0020state",
            "url": "classes/Core-Interfaces-AssetsCollection.html#method_reset"
        },                {
            "fqsen": "\\Core\\Interfaces\\View",
            "name": "View",
            "summary": "Main\u0020view\u0020interface",
            "url": "classes/Core-Interfaces-View.html"
        },                {
            "fqsen": "\\Core\\Interfaces\\View\u003A\u003ArenderFromCache\u0028\u0029",
            "name": "renderFromCache",
            "summary": "Get\u0020ResponseInterface\u0020from\u0020cache",
            "url": "classes/Core-Interfaces-View.html#method_renderFromCache"
        },                {
            "fqsen": "\\Core\\Interfaces\\View\u003A\u003AfetchFromCache\u0028\u0029",
            "name": "fetchFromCache",
            "summary": "Get\u0020string\u0020from\u0020cache",
            "url": "classes/Core-Interfaces-View.html#method_fetchFromCache"
        },                {
            "fqsen": "\\Core\\Interfaces\\View\u003A\u003Aclear\u0028\u0029",
            "name": "clear",
            "summary": "Clear\u0020all\u0020assigned\u0020vars",
            "url": "classes/Core-Interfaces-View.html#method_clear"
        },                {
            "fqsen": "\\Core\\Interfaces\\View\u003A\u003Aassign\u0028\u0029",
            "name": "assign",
            "summary": "Assign\u0020variable\u0020to\u0020template",
            "url": "classes/Core-Interfaces-View.html#method_assign"
        },                {
            "fqsen": "\\Core\\Interfaces\\View\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "Render\u0020the\u0020template\nReturn\u0020string\u0020data\u0020that\u0020you\u0020can\u0020add\u0020to\u0020cache\u0020or\u0020display",
            "url": "classes/Core-Interfaces-View.html#method_render"
        },                {
            "fqsen": "\\Core\\Interfaces\\View\u003A\u003Afetch\u0028\u0029",
            "name": "fetch",
            "summary": "Fetch\u0020template\u0020data\u0020as\u0020string\nReturn\u0020string\u0020data\u0020that\u0020you\u0020can\u0020add\u0020to\u0020cache\u0020or\u0020display",
            "url": "classes/Core-Interfaces-View.html#method_fetch"
        },                {
            "fqsen": "\\Core\\Interfaces\\View\u003A\u003AupdateResponse\u0028\u0029",
            "name": "updateResponse",
            "summary": "Update\u0020the\u0020response\u0020inside\u0020current\u0020View",
            "url": "classes/Core-Interfaces-View.html#method_updateResponse"
        },                {
            "fqsen": "\\Core\\Interfaces\\ViewAdapter",
            "name": "ViewAdapter",
            "summary": "Interface\u0020for\u0020factory\u0020that\u0020give\u0020us\u0020ready\u002Dto\u002Dconfig\u0020View\u0020interface",
            "url": "classes/Core-Interfaces-ViewAdapter.html"
        },                {
            "fqsen": "\\Core\\Interfaces\\ViewAdapter\u003A\u003AgetView\u0028\u0029",
            "name": "getView",
            "summary": "Get\u0020View\u0020element\u0020ready\u0020for\u0020use",
            "url": "classes/Core-Interfaces-ViewAdapter.html#method_getView"
        },                {
            "fqsen": "\\Core\\Interfaces\\ViewTopology",
            "name": "ViewTopology",
            "summary": "Topology\u0020\u002D\u0020main\u0020urls\u0020and\u0020paths",
            "url": "classes/Core-Interfaces-ViewTopology.html"
        },                {
            "fqsen": "\\Core\\Interfaces\\ViewTopology\u003A\u003AsetBaseUrl\u0028\u0029",
            "name": "setBaseUrl",
            "summary": "Get\u0020base\u0020URL\u0020of\u0020site",
            "url": "classes/Core-Interfaces-ViewTopology.html#method_setBaseUrl"
        },                {
            "fqsen": "\\Core\\Interfaces\\ViewTopology\u003A\u003AsetJsUrl\u0028\u0029",
            "name": "setJsUrl",
            "summary": "Get\u0020JavaScript\u0020URL",
            "url": "classes/Core-Interfaces-ViewTopology.html#method_setJsUrl"
        },                {
            "fqsen": "\\Core\\Interfaces\\ViewTopology\u003A\u003AsetLibsUrl\u0028\u0029",
            "name": "setLibsUrl",
            "summary": "Get\u0020Libs\u0020URL",
            "url": "classes/Core-Interfaces-ViewTopology.html#method_setLibsUrl"
        },                {
            "fqsen": "\\Core\\Interfaces\\ViewTopology\u003A\u003AsetCssUrl\u0028\u0029",
            "name": "setCssUrl",
            "summary": "Get\u0020Theme\u0020CSS\u0020URL",
            "url": "classes/Core-Interfaces-ViewTopology.html#method_setCssUrl"
        },                {
            "fqsen": "\\Core\\Interfaces\\ViewTopology\u003A\u003AsetFontsUrl\u0028\u0029",
            "name": "setFontsUrl",
            "summary": "Get\u0020theme\u0020fonts\u0020URL",
            "url": "classes/Core-Interfaces-ViewTopology.html#method_setFontsUrl"
        },                {
            "fqsen": "\\Core\\Interfaces\\ViewTopology\u003A\u003AsetImagesUrl\u0028\u0029",
            "name": "setImagesUrl",
            "summary": "Get\u0020theme\u0020images\u0020URL",
            "url": "classes/Core-Interfaces-ViewTopology.html#method_setImagesUrl"
        },                {
            "fqsen": "\\Core\\Interfaces\\ViewTopology\u003A\u003AsetThemeUrl\u0028\u0029",
            "name": "setThemeUrl",
            "summary": "Get\u0020theme\u0020URL",
            "url": "classes/Core-Interfaces-ViewTopology.html#method_setThemeUrl"
        },                {
            "fqsen": "\\Core\\Interfaces\\ViewTopology\u003A\u003AsetTemplatePath\u0028\u0029",
            "name": "setTemplatePath",
            "summary": "Set\u0020filesystem\u0020path\u0020to\u0020HTML\u0020templates",
            "url": "classes/Core-Interfaces-ViewTopology.html#method_setTemplatePath"
        },                {
            "fqsen": "\\Core\\Interfaces\\ViewTopology\u003A\u003AgetBaseUrl\u0028\u0029",
            "name": "getBaseUrl",
            "summary": "Get\u0020base\u0020URL\u0020of\u0020site",
            "url": "classes/Core-Interfaces-ViewTopology.html#method_getBaseUrl"
        },                {
            "fqsen": "\\Core\\Interfaces\\ViewTopology\u003A\u003AgetJsUrl\u0028\u0029",
            "name": "getJsUrl",
            "summary": "Get\u0020theme\u0020JavaScript\u0020URL",
            "url": "classes/Core-Interfaces-ViewTopology.html#method_getJsUrl"
        },                {
            "fqsen": "\\Core\\Interfaces\\ViewTopology\u003A\u003AgetCssUrl\u0028\u0029",
            "name": "getCssUrl",
            "summary": "Get\u0020theme\u0020CSS\u0020URL",
            "url": "classes/Core-Interfaces-ViewTopology.html#method_getCssUrl"
        },                {
            "fqsen": "\\Core\\Interfaces\\ViewTopology\u003A\u003AgetFontsUrl\u0028\u0029",
            "name": "getFontsUrl",
            "summary": "Get\u0020theme\u0020fonts\u0020URL",
            "url": "classes/Core-Interfaces-ViewTopology.html#method_getFontsUrl"
        },                {
            "fqsen": "\\Core\\Interfaces\\ViewTopology\u003A\u003AgetImagesUrl\u0028\u0029",
            "name": "getImagesUrl",
            "summary": "Get\u0020theme\u0020images\u0020URL",
            "url": "classes/Core-Interfaces-ViewTopology.html#method_getImagesUrl"
        },                {
            "fqsen": "\\Core\\Interfaces\\ViewTopology\u003A\u003AgetThemeUrl\u0028\u0029",
            "name": "getThemeUrl",
            "summary": "Get\u0020theme\u0020URL",
            "url": "classes/Core-Interfaces-ViewTopology.html#method_getThemeUrl"
        },                {
            "fqsen": "\\Core\\Interfaces\\ViewTopology\u003A\u003AgetLibsUrl\u0028\u0029",
            "name": "getLibsUrl",
            "summary": "Get\u0020libs\u0020URL",
            "url": "classes/Core-Interfaces-ViewTopology.html#method_getLibsUrl"
        },                {
            "fqsen": "\\Core\\Interfaces\\ViewTopology\u003A\u003AgetTemplatePath\u0028\u0029",
            "name": "getTemplatePath",
            "summary": "Get\u0020filesystem\u0020template\u0020path",
            "url": "classes/Core-Interfaces-ViewTopology.html#method_getTemplatePath"
        },                {
            "fqsen": "\\Core\\Interfaces\\WebPage",
            "name": "WebPage",
            "summary": "WebPage\u0020object\u0020\u002D\u0020all\u0020that\u0020needs\u0020to\u0020build\u0020web\u0020page",
            "url": "classes/Core-Interfaces-WebPage.html"
        },                {
            "fqsen": "\\Core\\Interfaces\\WebPage\u003A\u003AsetMicroFormatting\u0028\u0029",
            "name": "setMicroFormatting",
            "summary": "Set\u0020json\u0020for\u0020microformatting",
            "url": "classes/Core-Interfaces-WebPage.html#method_setMicroFormatting"
        },                {
            "fqsen": "\\Core\\Interfaces\\WebPage\u003A\u003AsetPageKeywords\u0028\u0029",
            "name": "setPageKeywords",
            "summary": "Set\u0020keywords.",
            "url": "classes/Core-Interfaces-WebPage.html#method_setPageKeywords"
        },                {
            "fqsen": "\\Core\\Interfaces\\WebPage\u003A\u003AsetMetaTag\u0028\u0029",
            "name": "setMetaTag",
            "summary": "Add\u0020meta\u002Dtag\u0020to\u0020webPage",
            "url": "classes/Core-Interfaces-WebPage.html#method_setMetaTag"
        },                {
            "fqsen": "\\Core\\Interfaces\\WebPage\u003A\u003AsetCacheControl\u0028\u0029",
            "name": "setCacheControl",
            "summary": "Add\u0020cache\u002Dcontrol\u0020meta\u0020tag\u0020to\u0020web\u0020page",
            "url": "classes/Core-Interfaces-WebPage.html#method_setCacheControl"
        },                {
            "fqsen": "\\Core\\Interfaces\\WebPage\u003A\u003AsetExpires\u0028\u0029",
            "name": "setExpires",
            "summary": "Add\u0020expires\u0020meta\u0020tag\u0020to\u0020web\u0020page",
            "url": "classes/Core-Interfaces-WebPage.html#method_setExpires"
        },                {
            "fqsen": "\\Core\\Interfaces\\WebPage\u003A\u003AsetLastModified\u0028\u0029",
            "name": "setLastModified",
            "summary": "Add\u0020Last\u002DModified\u0020meta\u0020tag\u0020to\u0020web\u0020page",
            "url": "classes/Core-Interfaces-WebPage.html#method_setLastModified"
        },                {
            "fqsen": "\\Core\\Interfaces\\WebPage\u003A\u003AsetPageTitle\u0028\u0029",
            "name": "setPageTitle",
            "summary": "Page\u0020title\u0020\u0028title\u0020tag\u0029",
            "url": "classes/Core-Interfaces-WebPage.html#method_setPageTitle"
        },                {
            "fqsen": "\\Core\\Interfaces\\WebPage\u003A\u003AsetPageHeader\u0028\u0029",
            "name": "setPageHeader",
            "summary": "Page\u0020header\u0020\u0028H1\u0029",
            "url": "classes/Core-Interfaces-WebPage.html#method_setPageHeader"
        },                {
            "fqsen": "\\Core\\Interfaces\\WebPage\u003A\u003AsetPageDescription\u0028\u0029",
            "name": "setPageDescription",
            "summary": "Page\u0020description",
            "url": "classes/Core-Interfaces-WebPage.html#method_setPageDescription"
        },                {
            "fqsen": "\\Core\\Interfaces\\WebPage\u003A\u003AsetImportMap\u0028\u0029",
            "name": "setImportMap",
            "summary": "JS\u0020import\u0020map",
            "url": "classes/Core-Interfaces-WebPage.html#method_setImportMap"
        },                {
            "fqsen": "\\Core\\Interfaces\\WebPage\u003A\u003AsetScriptCdn\u0028\u0029",
            "name": "setScriptCdn",
            "summary": "Plug\u0020any\u0020script\u0020from\u0020CDN\u0020or\u0020any\u0020URL",
            "url": "classes/Core-Interfaces-WebPage.html#method_setScriptCdn"
        },                {
            "fqsen": "\\Core\\Interfaces\\WebPage\u003A\u003AsetScript\u0028\u0029",
            "name": "setScript",
            "summary": "Plug\u0020script\u0020from\u0020theme\u0020folder",
            "url": "classes/Core-Interfaces-WebPage.html#method_setScript"
        },                {
            "fqsen": "\\Core\\Interfaces\\WebPage\u003A\u003AsetScriptFromGlobal\u0028\u0029",
            "name": "setScriptFromGlobal",
            "summary": "Plug\u0020script\u0020from\u0020libs\u0020folder",
            "url": "classes/Core-Interfaces-WebPage.html#method_setScriptFromGlobal"
        },                {
            "fqsen": "\\Core\\Interfaces\\WebPage\u003A\u003AsetScriptFromLib\u0028\u0029",
            "name": "setScriptFromLib",
            "summary": "Plug\u0020script\u0020from\u0020predefined\u0020library\u0020\u0028defined\u0020in\u0020WebPage\u0020obj\u0020constructor\u0029\nYou\u0020can\u0020put\u0020comma\u002Dseparated\u0020keys\u0020in\u0020\u0024scriptKey\u0020param",
            "url": "classes/Core-Interfaces-WebPage.html#method_setScriptFromLib"
        },                {
            "fqsen": "\\Core\\Interfaces\\WebPage\u003A\u003AappendScripts\u0028\u0029",
            "name": "appendScripts",
            "summary": "Put\u0020content\u0020after\u0020scripts\u0020section",
            "url": "classes/Core-Interfaces-WebPage.html#method_appendScripts"
        },                {
            "fqsen": "\\Core\\Interfaces\\WebPage\u003A\u003AapplyAssetCollection\u0028\u0029",
            "name": "applyAssetCollection",
            "summary": "Apply\u0020collection\u0020of\u0020assets\u0020to\u0020page",
            "url": "classes/Core-Interfaces-WebPage.html#method_applyAssetCollection"
        },                {
            "fqsen": "\\Core\\Interfaces\\WebPage\u003A\u003AsetStyleCdn\u0028\u0029",
            "name": "setStyleCdn",
            "summary": "Plug\u0020style\u0020from\u0020cdn\u0020or\u0020any\u0020URL",
            "url": "classes/Core-Interfaces-WebPage.html#method_setStyleCdn"
        },                {
            "fqsen": "\\Core\\Interfaces\\WebPage\u003A\u003AsetStyle\u0028\u0029",
            "name": "setStyle",
            "summary": "Plug\u0020style\u0020from\u0020theme\u0020folder",
            "url": "classes/Core-Interfaces-WebPage.html#method_setStyle"
        },                {
            "fqsen": "\\Core\\Interfaces\\WebPage\u003A\u003AsetStyleFromGlobal\u0028\u0029",
            "name": "setStyleFromGlobal",
            "summary": "Plug\u0020style\u0020from\u0020libs\u0020folder",
            "url": "classes/Core-Interfaces-WebPage.html#method_setStyleFromGlobal"
        },                {
            "fqsen": "\\Core\\Interfaces\\WebPage\u003A\u003AsetStyleFromLib\u0028\u0029",
            "name": "setStyleFromLib",
            "summary": "Plug\u0020style\u0020from\u0020library\u0020defined\u0020in\u0020webPage\u0020object\u0020constructor\nwhile\u0020it\u0020created\nYou\u0020can\u0020put\u0020comma\u002Dseparated\u0020style\u0020keys\u0020to\u0020\u0024styleKey\u0020param",
            "url": "classes/Core-Interfaces-WebPage.html#method_setStyleFromLib"
        },                {
            "fqsen": "\\Core\\Interfaces\\WebPage\u003A\u003AsetAttribute\u0028\u0029",
            "name": "setAttribute",
            "summary": "Set\u0020mixed\u0020attribute\u0020to\u0020use\u0020in\u0020webpage\u0020templates",
            "url": "classes/Core-Interfaces-WebPage.html#method_setAttribute"
        },                {
            "fqsen": "\\Core\\Interfaces\\WebPage\u003A\u003AgetWebpage\u0028\u0029",
            "name": "getWebpage",
            "summary": "Get\u0020result\u0020webpage\u0020array",
            "url": "classes/Core-Interfaces-WebPage.html#method_getWebpage"
        },                {
            "fqsen": "\\Core\\View\\AssetsCollectionGeneric",
            "name": "AssetsCollectionGeneric",
            "summary": "",
            "url": "classes/Core-View-AssetsCollectionGeneric.html"
        },                {
            "fqsen": "\\Core\\View\\AssetsCollectionGeneric\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Core-View-AssetsCollectionGeneric.html#method___construct"
        },                {
            "fqsen": "\\Core\\View\\AssetsCollectionGeneric\u003A\u003AsetScript\u0028\u0029",
            "name": "setScript",
            "summary": "Add\u0020new\u0020script\u0020to\u0020repository",
            "url": "classes/Core-View-AssetsCollectionGeneric.html#method_setScript"
        },                {
            "fqsen": "\\Core\\View\\AssetsCollectionGeneric\u003A\u003AsetStyle\u0028\u0029",
            "name": "setStyle",
            "summary": "Add\u0020new\u0020style\u0020to\u0020repository",
            "url": "classes/Core-View-AssetsCollectionGeneric.html#method_setStyle"
        },                {
            "fqsen": "\\Core\\View\\AssetsCollectionGeneric\u003A\u003AsetCollection\u0028\u0029",
            "name": "setCollection",
            "summary": "Add\u0020new\u0020Asset\u0020collection",
            "url": "classes/Core-View-AssetsCollectionGeneric.html#method_setCollection"
        },                {
            "fqsen": "\\Core\\View\\AssetsCollectionGeneric\u003A\u003AgetFilteredScripts\u0028\u0029",
            "name": "getFilteredScripts",
            "summary": "",
            "url": "classes/Core-View-AssetsCollectionGeneric.html#method_getFilteredScripts"
        },                {
            "fqsen": "\\Core\\View\\AssetsCollectionGeneric\u003A\u003AgetFilteredStyles\u0028\u0029",
            "name": "getFilteredStyles",
            "summary": "",
            "url": "classes/Core-View-AssetsCollectionGeneric.html#method_getFilteredStyles"
        },                {
            "fqsen": "\\Core\\View\\AssetsCollectionGeneric\u003A\u003AgetCollection\u0028\u0029",
            "name": "getCollection",
            "summary": "Get\u0020collection\u0020of\u0020assets",
            "url": "classes/Core-View-AssetsCollectionGeneric.html#method_getCollection"
        },                {
            "fqsen": "\\Core\\View\\AssetsCollectionGeneric\u003A\u003AgetScriptUrl\u0028\u0029",
            "name": "getScriptUrl",
            "summary": "Get\u0020scripts\u0020URl\u0020by\u0020key",
            "url": "classes/Core-View-AssetsCollectionGeneric.html#method_getScriptUrl"
        },                {
            "fqsen": "\\Core\\View\\AssetsCollectionGeneric\u003A\u003AgetStyleUrl\u0028\u0029",
            "name": "getStyleUrl",
            "summary": "Get\u0020style\u0020URL\u0020by\u0020key",
            "url": "classes/Core-View-AssetsCollectionGeneric.html#method_getStyleUrl"
        },                {
            "fqsen": "\\Core\\View\\AssetsCollectionGeneric\u003A\u003Areset\u0028\u0029",
            "name": "reset",
            "summary": "Reset\u0020state",
            "url": "classes/Core-View-AssetsCollectionGeneric.html#method_reset"
        },                {
            "fqsen": "\\Core\\View\\AssetsCollectionGeneric\u003A\u003A\u0024scripts",
            "name": "scripts",
            "summary": "Scripts\u0020library",
            "url": "classes/Core-View-AssetsCollectionGeneric.html#property_scripts"
        },                {
            "fqsen": "\\Core\\View\\AssetsCollectionGeneric\u003A\u003A\u0024styles",
            "name": "styles",
            "summary": "Styles\u0020library",
            "url": "classes/Core-View-AssetsCollectionGeneric.html#property_styles"
        },                {
            "fqsen": "\\Core\\View\\AssetsCollectionGeneric\u003A\u003A\u0024collections",
            "name": "collections",
            "summary": "Collections\u0020library",
            "url": "classes/Core-View-AssetsCollectionGeneric.html#property_collections"
        },                {
            "fqsen": "\\Core\\View\\ViewException",
            "name": "ViewException",
            "summary": "",
            "url": "classes/Core-View-ViewException.html"
        },                {
            "fqsen": "\\Core\\View\\ViewTopologyGeneric",
            "name": "ViewTopologyGeneric",
            "summary": "",
            "url": "classes/Core-View-ViewTopologyGeneric.html"
        },                {
            "fqsen": "\\Core\\View\\ViewTopologyGeneric\u003A\u003AgetBaseUrl\u0028\u0029",
            "name": "getBaseUrl",
            "summary": "Get\u0020base\u0020URL\u0020of\u0020site",
            "url": "classes/Core-View-ViewTopologyGeneric.html#method_getBaseUrl"
        },                {
            "fqsen": "\\Core\\View\\ViewTopologyGeneric\u003A\u003AgetThemeUrl\u0028\u0029",
            "name": "getThemeUrl",
            "summary": "Get\u0020theme\u0020URL",
            "url": "classes/Core-View-ViewTopologyGeneric.html#method_getThemeUrl"
        },                {
            "fqsen": "\\Core\\View\\ViewTopologyGeneric\u003A\u003AgetLibsUrl\u0028\u0029",
            "name": "getLibsUrl",
            "summary": "Get\u0020libs\u0020URL",
            "url": "classes/Core-View-ViewTopologyGeneric.html#method_getLibsUrl"
        },                {
            "fqsen": "\\Core\\View\\ViewTopologyGeneric\u003A\u003AgetCssUrl\u0028\u0029",
            "name": "getCssUrl",
            "summary": "Get\u0020theme\u0020CSS\u0020URL",
            "url": "classes/Core-View-ViewTopologyGeneric.html#method_getCssUrl"
        },                {
            "fqsen": "\\Core\\View\\ViewTopologyGeneric\u003A\u003AgetJsUrl\u0028\u0029",
            "name": "getJsUrl",
            "summary": "Get\u0020theme\u0020JavaScript\u0020URL",
            "url": "classes/Core-View-ViewTopologyGeneric.html#method_getJsUrl"
        },                {
            "fqsen": "\\Core\\View\\ViewTopologyGeneric\u003A\u003AgetFontsUrl\u0028\u0029",
            "name": "getFontsUrl",
            "summary": "Get\u0020theme\u0020fonts\u0020URL",
            "url": "classes/Core-View-ViewTopologyGeneric.html#method_getFontsUrl"
        },                {
            "fqsen": "\\Core\\View\\ViewTopologyGeneric\u003A\u003AgetImagesUrl\u0028\u0029",
            "name": "getImagesUrl",
            "summary": "Get\u0020theme\u0020images\u0020URL",
            "url": "classes/Core-View-ViewTopologyGeneric.html#method_getImagesUrl"
        },                {
            "fqsen": "\\Core\\View\\ViewTopologyGeneric\u003A\u003AgetTemplatePath\u0028\u0029",
            "name": "getTemplatePath",
            "summary": "Get\u0020filesystem\u0020template\u0020path",
            "url": "classes/Core-View-ViewTopologyGeneric.html#method_getTemplatePath"
        },                {
            "fqsen": "\\Core\\View\\ViewTopologyGeneric\u003A\u003AsetBaseUrl\u0028\u0029",
            "name": "setBaseUrl",
            "summary": "Get\u0020base\u0020URL\u0020of\u0020site",
            "url": "classes/Core-View-ViewTopologyGeneric.html#method_setBaseUrl"
        },                {
            "fqsen": "\\Core\\View\\ViewTopologyGeneric\u003A\u003AsetThemeUrl\u0028\u0029",
            "name": "setThemeUrl",
            "summary": "Get\u0020theme\u0020URL",
            "url": "classes/Core-View-ViewTopologyGeneric.html#method_setThemeUrl"
        },                {
            "fqsen": "\\Core\\View\\ViewTopologyGeneric\u003A\u003AsetLibsUrl\u0028\u0029",
            "name": "setLibsUrl",
            "summary": "Get\u0020Libs\u0020URL",
            "url": "classes/Core-View-ViewTopologyGeneric.html#method_setLibsUrl"
        },                {
            "fqsen": "\\Core\\View\\ViewTopologyGeneric\u003A\u003AsetCssUrl\u0028\u0029",
            "name": "setCssUrl",
            "summary": "Get\u0020Theme\u0020CSS\u0020URL",
            "url": "classes/Core-View-ViewTopologyGeneric.html#method_setCssUrl"
        },                {
            "fqsen": "\\Core\\View\\ViewTopologyGeneric\u003A\u003AsetJsUrl\u0028\u0029",
            "name": "setJsUrl",
            "summary": "Get\u0020JavaScript\u0020URL",
            "url": "classes/Core-View-ViewTopologyGeneric.html#method_setJsUrl"
        },                {
            "fqsen": "\\Core\\View\\ViewTopologyGeneric\u003A\u003AsetFontsUrl\u0028\u0029",
            "name": "setFontsUrl",
            "summary": "Get\u0020theme\u0020fonts\u0020URL",
            "url": "classes/Core-View-ViewTopologyGeneric.html#method_setFontsUrl"
        },                {
            "fqsen": "\\Core\\View\\ViewTopologyGeneric\u003A\u003AsetImagesUrl\u0028\u0029",
            "name": "setImagesUrl",
            "summary": "Get\u0020theme\u0020images\u0020URL",
            "url": "classes/Core-View-ViewTopologyGeneric.html#method_setImagesUrl"
        },                {
            "fqsen": "\\Core\\View\\ViewTopologyGeneric\u003A\u003AsetTemplatePath\u0028\u0029",
            "name": "setTemplatePath",
            "summary": "Set\u0020filesystem\u0020path\u0020to\u0020HTML\u0020templates",
            "url": "classes/Core-View-ViewTopologyGeneric.html#method_setTemplatePath"
        },                {
            "fqsen": "\\Core\\View\\ViewTopologyGeneric\u003A\u003AaddTemplatePath\u0028\u0029",
            "name": "addTemplatePath",
            "summary": "",
            "url": "classes/Core-View-ViewTopologyGeneric.html#method_addTemplatePath"
        },                {
            "fqsen": "\\Core\\View\\ViewTopologyGeneric\u003A\u003A\u0024templatePath",
            "name": "templatePath",
            "summary": "Array\u0020of\u0020paths\u0020for\u0020templates",
            "url": "classes/Core-View-ViewTopologyGeneric.html#property_templatePath"
        },                {
            "fqsen": "\\Core\\View\\ViewTopologyGeneric\u003A\u003A\u0024url",
            "name": "url",
            "summary": "Base\u0020urls\u0020array",
            "url": "classes/Core-View-ViewTopologyGeneric.html#property_url"
        },                {
            "fqsen": "\\Core\\View\\ViewTrait",
            "name": "ViewTrait",
            "summary": "",
            "url": "classes/Core-View-ViewTrait.html"
        },                {
            "fqsen": "\\Core\\View\\ViewTrait\u003A\u003Aclear\u0028\u0029",
            "name": "clear",
            "summary": "",
            "url": "classes/Core-View-ViewTrait.html#method_clear"
        },                {
            "fqsen": "\\Core\\View\\ViewTrait\u003A\u003Aassign\u0028\u0029",
            "name": "assign",
            "summary": "Assign\u0020variable\u0020to\u0020template",
            "url": "classes/Core-View-ViewTrait.html#method_assign"
        },                {
            "fqsen": "\\Core\\View\\ViewTrait\u003A\u003ArenderFromCache\u0028\u0029",
            "name": "renderFromCache",
            "summary": "",
            "url": "classes/Core-View-ViewTrait.html#method_renderFromCache"
        },                {
            "fqsen": "\\Core\\View\\ViewTrait\u003A\u003AfetchFromCache\u0028\u0029",
            "name": "fetchFromCache",
            "summary": "",
            "url": "classes/Core-View-ViewTrait.html#method_fetchFromCache"
        },                {
            "fqsen": "\\Core\\View\\ViewTrait\u003A\u003AtryAddToCache\u0028\u0029",
            "name": "tryAddToCache",
            "summary": "Try\u0020to\u0020add\u0020to\u0020cache",
            "url": "classes/Core-View-ViewTrait.html#method_tryAddToCache"
        },                {
            "fqsen": "\\Core\\View\\ViewTrait\u003A\u003AgetCacheName\u0028\u0029",
            "name": "getCacheName",
            "summary": "",
            "url": "classes/Core-View-ViewTrait.html#method_getCacheName"
        },                {
            "fqsen": "\\Core\\View\\ViewTrait\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "",
            "url": "classes/Core-View-ViewTrait.html#method_render"
        },                {
            "fqsen": "\\Core\\View\\ViewTrait\u003A\u003AupdateResponse\u0028\u0029",
            "name": "updateResponse",
            "summary": "",
            "url": "classes/Core-View-ViewTrait.html#method_updateResponse"
        },                {
            "fqsen": "\\Core\\View\\ViewTrait\u003A\u003A\u0024eventDispatcher",
            "name": "eventDispatcher",
            "summary": "",
            "url": "classes/Core-View-ViewTrait.html#property_eventDispatcher"
        },                {
            "fqsen": "\\Core\\View\\ViewTrait\u003A\u003A\u0024response",
            "name": "response",
            "summary": "",
            "url": "classes/Core-View-ViewTrait.html#property_response"
        },                {
            "fqsen": "\\Core\\View\\ViewTrait\u003A\u003A\u0024request",
            "name": "request",
            "summary": "",
            "url": "classes/Core-View-ViewTrait.html#property_request"
        },                {
            "fqsen": "\\Core\\View\\ViewTrait\u003A\u003A\u0024cache",
            "name": "cache",
            "summary": "",
            "url": "classes/Core-View-ViewTrait.html#property_cache"
        },                {
            "fqsen": "\\Core\\View\\ViewTrait\u003A\u003A\u0024vars",
            "name": "vars",
            "summary": "",
            "url": "classes/Core-View-ViewTrait.html#property_vars"
        },                {
            "fqsen": "\\Core\\View\\WebPageGeneric",
            "name": "WebPageGeneric",
            "summary": "",
            "url": "classes/Core-View-WebPageGeneric.html"
        },                {
            "fqsen": "\\Core\\View\\WebPageGeneric\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "WebPageGeneric\u0020constructor",
            "url": "classes/Core-View-WebPageGeneric.html#method___construct"
        },                {
            "fqsen": "\\Core\\View\\WebPageGeneric\u003A\u003AsetMicroFormatting\u0028\u0029",
            "name": "setMicroFormatting",
            "summary": "Set\u0020json\u0020for\u0020microformatting",
            "url": "classes/Core-View-WebPageGeneric.html#method_setMicroFormatting"
        },                {
            "fqsen": "\\Core\\View\\WebPageGeneric\u003A\u003AsetPageKeywords\u0028\u0029",
            "name": "setPageKeywords",
            "summary": "Set\u0020keywords.",
            "url": "classes/Core-View-WebPageGeneric.html#method_setPageKeywords"
        },                {
            "fqsen": "\\Core\\View\\WebPageGeneric\u003A\u003AsetMetaTag\u0028\u0029",
            "name": "setMetaTag",
            "summary": "Add\u0020meta\u002Dtag\u0020to\u0020webPage",
            "url": "classes/Core-View-WebPageGeneric.html#method_setMetaTag"
        },                {
            "fqsen": "\\Core\\View\\WebPageGeneric\u003A\u003AsetCacheControl\u0028\u0029",
            "name": "setCacheControl",
            "summary": "Add\u0020cache\u002Dcontrol\u0020meta\u0020tag\u0020to\u0020web\u0020page",
            "url": "classes/Core-View-WebPageGeneric.html#method_setCacheControl"
        },                {
            "fqsen": "\\Core\\View\\WebPageGeneric\u003A\u003AsetExpires\u0028\u0029",
            "name": "setExpires",
            "summary": "Add\u0020expires\u0020meta\u0020tag\u0020to\u0020web\u0020page",
            "url": "classes/Core-View-WebPageGeneric.html#method_setExpires"
        },                {
            "fqsen": "\\Core\\View\\WebPageGeneric\u003A\u003AsetLastModified\u0028\u0029",
            "name": "setLastModified",
            "summary": "Add\u0020Last\u002DModified\u0020meta\u0020tag\u0020to\u0020web\u0020page",
            "url": "classes/Core-View-WebPageGeneric.html#method_setLastModified"
        },                {
            "fqsen": "\\Core\\View\\WebPageGeneric\u003A\u003AsetPageTitle\u0028\u0029",
            "name": "setPageTitle",
            "summary": "Page\u0020title\u0020\u0028title\u0020tag\u0029",
            "url": "classes/Core-View-WebPageGeneric.html#method_setPageTitle"
        },                {
            "fqsen": "\\Core\\View\\WebPageGeneric\u003A\u003AsetPageHeader\u0028\u0029",
            "name": "setPageHeader",
            "summary": "Page\u0020header\u0020\u0028H1\u0029",
            "url": "classes/Core-View-WebPageGeneric.html#method_setPageHeader"
        },                {
            "fqsen": "\\Core\\View\\WebPageGeneric\u003A\u003AsetPageDescription\u0028\u0029",
            "name": "setPageDescription",
            "summary": "Page\u0020description",
            "url": "classes/Core-View-WebPageGeneric.html#method_setPageDescription"
        },                {
            "fqsen": "\\Core\\View\\WebPageGeneric\u003A\u003AsetImportMap\u0028\u0029",
            "name": "setImportMap",
            "summary": "JS\u0020import\u0020map",
            "url": "classes/Core-View-WebPageGeneric.html#method_setImportMap"
        },                {
            "fqsen": "\\Core\\View\\WebPageGeneric\u003A\u003AsetScriptCdn\u0028\u0029",
            "name": "setScriptCdn",
            "summary": "Plug\u0020any\u0020script\u0020from\u0020CDN\u0020or\u0020any\u0020URL",
            "url": "classes/Core-View-WebPageGeneric.html#method_setScriptCdn"
        },                {
            "fqsen": "\\Core\\View\\WebPageGeneric\u003A\u003AsetScript\u0028\u0029",
            "name": "setScript",
            "summary": "Plug\u0020script\u0020from\u0020theme\u0020folder",
            "url": "classes/Core-View-WebPageGeneric.html#method_setScript"
        },                {
            "fqsen": "\\Core\\View\\WebPageGeneric\u003A\u003AsetScriptFromGlobal\u0028\u0029",
            "name": "setScriptFromGlobal",
            "summary": "Plug\u0020script\u0020from\u0020libs\u0020folder",
            "url": "classes/Core-View-WebPageGeneric.html#method_setScriptFromGlobal"
        },                {
            "fqsen": "\\Core\\View\\WebPageGeneric\u003A\u003AsetScriptFromLib\u0028\u0029",
            "name": "setScriptFromLib",
            "summary": "Plug\u0020script\u0020from\u0020predefined\u0020library\u0020\u0028defined\u0020in\u0020WebPage\u0020obj\u0020constructor\u0029\nYou\u0020can\u0020put\u0020comma\u002Dseparated\u0020keys\u0020in\u0020\u0024scriptKey\u0020param",
            "url": "classes/Core-View-WebPageGeneric.html#method_setScriptFromLib"
        },                {
            "fqsen": "\\Core\\View\\WebPageGeneric\u003A\u003AsetStyleCdn\u0028\u0029",
            "name": "setStyleCdn",
            "summary": "Plug\u0020style\u0020from\u0020cdn\u0020or\u0020any\u0020URL",
            "url": "classes/Core-View-WebPageGeneric.html#method_setStyleCdn"
        },                {
            "fqsen": "\\Core\\View\\WebPageGeneric\u003A\u003AsetStyle\u0028\u0029",
            "name": "setStyle",
            "summary": "Plug\u0020style\u0020from\u0020theme\u0020folder",
            "url": "classes/Core-View-WebPageGeneric.html#method_setStyle"
        },                {
            "fqsen": "\\Core\\View\\WebPageGeneric\u003A\u003AsetStyleFromGlobal\u0028\u0029",
            "name": "setStyleFromGlobal",
            "summary": "Plug\u0020style\u0020from\u0020libs\u0020folder",
            "url": "classes/Core-View-WebPageGeneric.html#method_setStyleFromGlobal"
        },                {
            "fqsen": "\\Core\\View\\WebPageGeneric\u003A\u003AsetStyleFromLib\u0028\u0029",
            "name": "setStyleFromLib",
            "summary": "Plug\u0020style\u0020from\u0020library\u0020defined\u0020in\u0020webPage\u0020object\u0020constructor\nwhile\u0020it\u0020created\nYou\u0020can\u0020put\u0020comma\u002Dseparated\u0020style\u0020keys\u0020to\u0020\u0024styleKey\u0020param",
            "url": "classes/Core-View-WebPageGeneric.html#method_setStyleFromLib"
        },                {
            "fqsen": "\\Core\\View\\WebPageGeneric\u003A\u003AappendScripts\u0028\u0029",
            "name": "appendScripts",
            "summary": "Put\u0020content\u0020after\u0020scripts\u0020section",
            "url": "classes/Core-View-WebPageGeneric.html#method_appendScripts"
        },                {
            "fqsen": "\\Core\\View\\WebPageGeneric\u003A\u003AapplyAssetCollection\u0028\u0029",
            "name": "applyAssetCollection",
            "summary": "Apply\u0020collection\u0020of\u0020assets\u0020to\u0020page",
            "url": "classes/Core-View-WebPageGeneric.html#method_applyAssetCollection"
        },                {
            "fqsen": "\\Core\\View\\WebPageGeneric\u003A\u003AsetAttribute\u0028\u0029",
            "name": "setAttribute",
            "summary": "Set\u0020mixed\u0020attribute\u0020to\u0020use\u0020in\u0020webpage\u0020templates",
            "url": "classes/Core-View-WebPageGeneric.html#method_setAttribute"
        },                {
            "fqsen": "\\Core\\View\\WebPageGeneric\u003A\u003AgetWebpage\u0028\u0029",
            "name": "getWebpage",
            "summary": "Get\u0020result\u0020webpage\u0020array",
            "url": "classes/Core-View-WebPageGeneric.html#method_getWebpage"
        },                {
            "fqsen": "\\Core\\View\\WebPageGeneric\u003A\u003A\u0024assetsCollection",
            "name": "assetsCollection",
            "summary": "AssetsCollection",
            "url": "classes/Core-View-WebPageGeneric.html#property_assetsCollection"
        },                {
            "fqsen": "\\Core\\View\\WebPageGeneric\u003A\u003A\u0024attributes",
            "name": "attributes",
            "summary": "Library\u0020of\u0020page\u0020attributes",
            "url": "classes/Core-View-WebPageGeneric.html#property_attributes"
        },                {
            "fqsen": "\\Core\\View\\WebPageGeneric\u003A\u003A\u0024viewTopology",
            "name": "viewTopology",
            "summary": "Topology\u0020of\u0020paths\u0020used\u0020by\u0020rendering\u0020engines",
            "url": "classes/Core-View-WebPageGeneric.html#property_viewTopology"
        },                {
            "fqsen": "\\Core\\View\\WebPageGeneric\u003A\u003A\u0024jsImportMap",
            "name": "jsImportMap",
            "summary": "JS\u0020importmanp\u0020data",
            "url": "classes/Core-View-WebPageGeneric.html#property_jsImportMap"
        },                {
            "fqsen": "\\Core\\View\\WebPageGeneric\u003A\u003A\u0024vars",
            "name": "vars",
            "summary": "Page\u0020variables\u0020for\u0020use\u0020in\u0020templates",
            "url": "classes/Core-View-WebPageGeneric.html#property_vars"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Core\\Events",
            "name": "Events",
            "summary": "",
            "url": "namespaces/core-events.html"
        },                {
            "fqsen": "\\Core",
            "name": "Core",
            "summary": "",
            "url": "namespaces/core.html"
        },                {
            "fqsen": "\\Core\\Interfaces",
            "name": "Interfaces",
            "summary": "",
            "url": "namespaces/core-interfaces.html"
        },                {
            "fqsen": "\\Core\\View",
            "name": "View",
            "summary": "",
            "url": "namespaces/core-view.html"
        }            ]
);
